// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_follow.sql

package database

import (
	"context"
)

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM feed_follows
WHERE user_id = (
    SELECT id from users where users.name = $1
) AND feed_id = (
    SELECT id from feeds where feeds.url = $2
)
`

type DeleteFollowParams struct {
	Name string
	Url  string
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollow, arg.Name, arg.Url)
	return err
}
